image: registry.git.lacl.fr/barbot/boltzgen:latest

before_script:
  - eval `opam config env`
  - opam update
  - opam install ocaml-compiler-libs dune cmdliner js_of_ocaml-toplevel


boltzgen:
    stage : build
    script:
        - dune build @install
        - dune runtest

pages:
  stage: deploy
  script:
    - make web
    - mv website public
  artifacts:
    paths:
#      - _build/default/web-view/*.js
       - public
