platform:
  - x64

environment:
  CYG_ROOT: "C:\\cygwin64"
  CYG_CACHE: C:/cygwin64/var/cache/setup
  CYG_MIRROR: http://mirrors.kernel.org/sourceware/cygwin/
  CYG_BASH: "%CYG_ROOT%\\bin\\bash -lc"
  CYG_ARCH: "x86_64"
  CYGWIN: "winsymlinks:native"
  CUSTOM_OPAM: "1"
  OPAM_COMP: "4.06.0+mingw64c"

install:
  - cmd: git config core.symlinks true
  - cmd: git reset --hard
  - 'appveyor DownloadFile http://cygwin.com/setup-%CYG_ARCH%.exe -FileName setup.exe'
  - 'setup.exe -gqnNdO -R "%CYG_ROOT%" -s "%CYG_MIRROR%" -l "%CYG_CACHE%" -P make,git,rsync,perl,gcc-core,gcc-g++,libncurses-devel,unzip,libmpfr-devel,patch,flexdll,libglpk-devel'
  - '%CYG_ROOT%/bin/bash -lc "cygcheck -dc cygwin gcc-core"'

build_script:
  - "%CYG_BASH% '${APPVEYOR_BUILD_FOLDER}/scripts/appveyor.sh'"

artifacts:
  - path: "vpnkit.exe"
  - path: "OSS-LICENSES"
  - path: "COMMIT"
