# custom .travis.yml
# based on http://anil.recoil.org/2013/09/30/travis-and-ocaml.html

language: c
sudo: required

install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh

script: bash -ex .travis-opam.sh

env:
  - OCAML_VERSION=4.02
  - OCAML_VERSION=4.03
  - OCAML_VERSION=4.06
  - OCAML_VERSION=4.07

os:
  - linux

after_script:
  - opam install -y ocveralls
  - "`opam config var bin`/ocveralls _build/default/tests/coverage*.out \
     --prefix _build/default/tests/ \
     --send"

notifications:
  email: false
