build-and-test:
  image: ocaml/opam2:debian-stable
  script:
    - opam pin --no-action uecc .
    - opam depext uecc
    - opam install --deps-only -t .
    - dune build
    - dune runtest
    - opam install .
