build-and-test:
  image: ocaml/opam2:4.09
  script:
    - opam repository set-url default https://opam.ocaml.org
    - opam update
    - opam pin --no-action lwt-canceler.dev .
    - opam depext lwt-canceler
    - opam install --deps-only lwt-canceler
    - dune build
    - opam install --deps-only --with-test .
    - dune runtest

pages:
  image: ocaml/opam2:4.09
  artifacts:
    paths:
    - public/
  only:
    - master
  script:
    - opam repository set-url default https://opam.ocaml.org
    - opam update
    - opam pin --no-action lwt-canceler.dev .
    - opam depext lwt-canceler
    - opam install --deps-only lwt-canceler
    - opam depext odoc
    - opam install odoc
    - dune build @doc
    - mv _build/default/_doc/_html public/
