language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  - PACKAGE=bitstring OCAML_VERSION=4.02
  - PACKAGE=bitstring OCAML_VERSION=4.03
  - PACKAGE=bitstring OCAML_VERSION=4.04
  - PACKAGE=bitstring OCAML_VERSION=4.05
  - PACKAGE=bitstring OCAML_VERSION=4.06
os:
  - linux
  - osx
