language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
- docker
env:
  global:
  - PINS="containers:."
  - DISTRO="ubuntu-16.04"
  matrix:
  - PACKAGE="containers" OCAML_VERSION="4.02.3" EXTRA_DEPS="base-threads base-unix"
  - PACKAGE="containers" OCAML_VERSION="4.03.0" EXTRA_DEPS="base-threads base-unix"
  - PACKAGE="containers" OCAML_VERSION="4.04.2" EXTRA_DEPS="base-threads base-unix"
  - PACKAGE="containers" OCAML_VERSION="4.05.0" EXTRA_DEPS="base-threads base-unix"
  - PACKAGE="containers" OCAML_VERSION="4.06.0" EXTRA_DEPS="base-threads base-unix"
  - PACKAGE="containers" OCAML_VERSION="4.07.0" EXTRA_DEPS="base-threads base-unix"
