version: '3.7'

networks:
  oraft:

x-node: &default-node
  build:
    context: .
    dockerfile: ${DOCKER_CONF_DIR}/Dockerfile
  networks:
  - oraft
  restart: always

services:
  oraft-1:
    <<: *default-node
    volumes:
    - ./${DOCKER_CONF_DIR}/oraft-1:/workspace
    ports:
    - 7891
    - '8181:8181'
    container_name: oraft-1
  oraft-2:
    <<: *default-node
    volumes:
    - ./${DOCKER_CONF_DIR}/oraft-2:/workspace
    ports:
    - 7891
    - '8182:8181'
    container_name: oraft-2
  oraft-3:
    <<: *default-node
    volumes:
    - ./${DOCKER_CONF_DIR}/oraft-3:/workspace
    ports:
    - 7891
    - '8183:8181'
    container_name: oraft-3
  oraft-4:
    <<: *default-node
    volumes:
    - ./${DOCKER_CONF_DIR}/oraft-4:/workspace
    ports:
    - 7891
    - '8184:8181'
    container_name: oraft-4
  oraft-5:
    <<: *default-node
    volumes:
    - ./${DOCKER_CONF_DIR}/oraft-5:/workspace
    ports:
    - 7891
    - '8185:8181'
    container_name: oraft-5
  chaos-pause:
    image: gaiaadm/pumba
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    command: "--log-level info --random --interval 7s pause --duration 2s re2:oraft-*"
    depends_on:
    - oraft-1
    - oraft-2
    - oraft-3
    - oraft-4
    - oraft-5
# chaos-delay:
#   image: gaiaadm/pumba
#   volumes:
#   - /var/run/docker.sock:/var/run/docker.sock
#   command: "--log-level info --random --interval 11s netem --tc-image gaiadocker/iproute2 --duration 4s delay re2:oraft-*"
#   depends_on:
#   - oraft-1
#   - oraft-2
#   - oraft-3
#   - oraft-4
#   - oraft-5

