language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex ./.travis-docker.sh
env:
  global:
  - DISTRO="ubuntu"
  - PINS="dispatch-js:. dispatch:."
  - PACKAGE="dispatch"
  - TESTS=true
  - POST_INSTALL_HOOK="opam install --with-test dispatch-js"
  matrix:
  - OCAML_VERSION="4.07"
  - OCAML_VERSION="4.06"
  - OCAML_VERSION="4.05"
