name: build
on: [push]
jobs:
  run:
    name: Build
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [macos-latest, ubuntu-latest, windows-latest]
        ocaml-version: [ '4.08.0' ]
    steps:
    - uses: actions/checkout@main
    - uses: avsm/setup-ocaml@master
      with:
        ocaml-version: ${{ matrix.ocaml-version }}
    - run: opam pin -n .
    - run: opam depext -yt containers containers-data containers-thread
    - run: opam install -t . --deps-only
      if: ${{ matrix.operating-system != 'windows-latest' }}
    - run: opam install . --deps-only  # no test deps
      if: ${{ matrix.operating-system == 'windows-latest' }}
    - run: opam exec -- dune build
    - run: opam exec -- dune runtest
      if: ${{ matrix.operating-system != 'windows-latest' }}
