language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
  - redis-server
  - docker
env:
  global:
    - PINS="redis:. redis-sync:. redis-lwt:."
    - DISTRO="ubuntu-16.04"
  matrix:
    - PACKAGE="redis-lwt" OCAML_VERSION=4.02 PINS="redis:."
    - PACKAGE="redis-lwt" OCAML_VERSION=4.03 PINS="redis:."
    - PACKAGE="redis-lwt" OCAML_VERSION=4.04 PINS="redis:."
    - PACKAGE="redis-lwt" OCAML_VERSION=4.05 PINS="redis:."
    - PACKAGE="redis-lwt" OCAML_VERSION=4.06 PINS="redis:."
    - PACKAGE="redis-lwt" OCAML_VERSION=4.07 PINS="redis:."
    - PACKAGE="redis-lwt" OCAML_VERSION=4.08 PINS="redis:."
