language: c
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
  - wget https://raw.githubusercontent.com/simonjbeaumont/ocaml-travis-coveralls/master/travis-coveralls.sh
script: bash -ex .travis-opam.sh
sudo: required
dist: trusty
env:
  global:
    - PACKAGE="qcow-tool" OCAML_VERSION=4.03
    - PINS="qcow:."
    - COV_CONF="export TESTS=--enable-tests"
    - PRE_INSTALL_HOOK="sudo apt-get install qemu-utils -y"
