variables:
  GIT_STRATEGY: "fetch"
  GIT_DEPTH: "1"

stages:
  - build

.build_template: &build_definition
  image: ocaml/opam2
  stage: build
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - _build
      - ~/.opam
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - _build/
    expire_in: 1 day
  tags:
    - gitlab-org
  script:
    - sudo apt-get update
    - sudo apt-get install -y
        autoconf
        automake
        libbz2-dev
        libev-dev
        libgmp-dev
        libhidapi-dev
        m4
        pandoc
        perl
        pkg-config
        python3
        python3-yaml
        zlib1g-dev
    - opam init
    - opam remote set-url default git://github.com/ocaml/opam-repository.git
    - opam remote
    - opam show dune
    - opam depext
    - opam install dune.2.7.1
    - opam install --with-test --with-doc --deps-only .
    - make all
    - make test
    - opam clean

build:
  <<: *build_definition
  image: ocaml/opam2

build403:
  <<: *build_definition
  image: ocaml/opam2:4.03

# make testing a separate job to make sure that all tests have their
# dependencies set up correctly. To test for this, we do not run a full build
# before running "make test". We also test whether the dependencies for each
# subdirectory are setup correctly, by running dune clean between each
# invocation.
test:
  image: ocaml/opam2
  stage: build
  script:
    - sudo apt-get update
    - sudo apt-get install -y
        autoconf
        automake
        libbz2-dev
        libev-dev
        libgmp-dev
        libhidapi-dev
        m4
        pandoc
        perl
        pkg-config
        python3
        python3-yaml
        zlib1g-dev
    - opam init
    - opam remote set-url default git://github.com/ocaml/opam-repository.git
    - opam remote
    - opam depext
    - opam install --with-test --with-doc --deps-only .
    - for d in src/*; do dune runtest $d; dune clean; done
    - dune clean
    - make test
    - opam clean

# make the linting a separate job because:
#   - installing ocamlformat and dependencies from opam takes 5 minutes
#   - avoiding to taint the build environment with additional packages
lint:
  image: ocaml/opam2
  stage: build
  script:
    - sudo apt-get update
    - sudo apt-get install -y m4
    - opam init
    - opam remote set-url default git://github.com/ocaml/opam-repository.git
      # rebuild dose3.opam to check whether the file in git matches what is
      # generated by dune
    - opam install dune.2.7.1
    - dune build dose3.opam
    - git diff --exit-code
      # check whether source code complies with ocamlformat
    - opam install ocamlformat
    - dune build @fmt
    - opam clean

pages:
  image: ocaml/opam2
  stage: build
  only:
    - master
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - _build
      - ~/.opam
      - doc/rtd/_build
  artifacts:
    paths:
      - public/
  script:
    - sudo apt-get update
    - sudo apt-get install -y
        autoconf
        automake
        graphviz
        libbz2-dev
        libev-dev
        libgmp-dev
        libhidapi-dev
        m4
        pandoc
        pkg-config
        python3
        python3-virtualenv
        python3-yaml
        texlive-latex-base
        texlive-latex-extra
        zlib1g-dev
    - opam init
    - opam remote set-url default git://github.com/ocaml/opam-repository.git
    - opam install --with-test --with-doc --deps-only .
    - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 -
    - source $HOME/.poetry/env
    - env --chdir=doc/rtd poetry install
    - make doc
    - mkdir public
    - cp -a doc/rtd/_build/* public
    - cp -a _build/default/_doc/_html public/api

opam-debian:
  image: ocaml/opam:debian
  stage: build
  script:
    - opam remote set-url default git://github.com/ocaml/opam-repository.git
    - opam pin add -yn .
    - opam depext -uiy --with-test dose3

opam-alpine:
  image: ocaml/opam:alpine
  stage: build
  script:
    - opam remote set-url default git://github.com/ocaml/opam-repository.git
    - opam pin add -yn .
    - opam depext -uiy --with-test dose3
