language: c
sudo: required
addons:
  apt:
    packages:
      - rabbitmq-server
services:
  - rabbitmq

install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  matrix:
  - OCAML_VERSION=4.04 PACKAGE="amqp-client-async" POST_INSTALL_HOOK="dune build @integration -p amqp-client-async"
  - OCAML_VERSION=4.04 PACKAGE="amqp-client-lwt"   POST_INSTALL_HOOK="dune build @integration -p amqp-client-lwt"
  - OCAML_VERSION=4.09 PACKAGE="amqp-client-async" POST_INSTALL_HOOK="dune build @integration -p amqp-client-async"
  - OCAML_VERSION=4.09 PACKAGE="amqp-client-lwt"   POST_INSTALL_HOOK="dune build @integration -p amqp-client-lwt"
  - OCAML_VERSION=4.10 PACKAGE="amqp-client-async" POST_INSTALL_HOOK="dune build @integration -p amqp-client-async"
  - OCAML_VERSION=4.10 PACKAGE="amqp-client-lwt"   POST_INSTALL_HOOK="dune build @integration -p amqp-client-lwt"

  global:
  - DEPOPTS="*"
  - TESTS=true
  - PINS="amqp-client:. amqp-client-async:. amqp-client-lwt:."

os:
  - linux
