language: c
services:
  - redis-server
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  - PACKAGE="redis-lwt" OCAML_VERSION=4.02 PINS="redis:."
  - PACKAGE="redis-lwt" OCAML_VERSION=4.03 PINS="redis:."
  - PACKAGE="redis-lwt" OCAML_VERSION=4.04 PINS="redis:."
  - PACKAGE="redis-lwt" OCAML_VERSION=4.05 PINS="redis:."
  - PACKAGE="redis-lwt" OCAML_VERSION=4.06 PINS="redis:."
  - PACKAGE="redis-lwt" OCAML_VERSION=latest PINS="redis:."
