image: ocaml/opam2:4.09

before_script:
  - sudo apt install -y m4 libgmp-dev
  - opam remote add official https://opam.ocaml.org/
  - opam update
  - opam install -y --deps-only .

stages:
  - build

build:
  stage: build
  script:
  - make
