image: registry.git.lacl.fr/barbot/boltzgen:latest

before_script:
  - eval `opam config env`
  - opam update
  - opam install ocaml-compiler-libs dune cmdliner 


boltzgen:
    stage : build
    script:
        - dune build
        - dune runtest

