name: "Build and test"
on: [push]
jobs:
  run:
    name: "Build and test"
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        ocaml-version: ['4.07.1', '4.08.1', '4.09.0', '4.10.0']
    steps:
    - uses: actions/checkout@master

    - name: Setup OCaml
      uses: avsm/setup-ocaml@master
      with:
        ocaml-version: ${{ matrix.ocaml-version }}

    - run: opam pin add ppx_rapper --no-action .
    - run: OPAMSOLVERTIMEOUT=3600 opam depext -yt ppx_rapper
    - run: OPAMSOLVERTIMEOUT=3600 opam install -t . --deps-only
    - run: opam exec -- dune build
    - run: opam exec -- dune runtest
