language: c
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
  - wget https://raw.githubusercontent.com/xapi-project/xapi-travis-scripts/master/coverage.sh
script:
  - cp crc.opam opam && bash -ex .travis-opam.sh
env:
  global:
    - PACKAGE=crc
  matrix:
    - OCAML_VERSION=4.06
    - OCAML_VERSION=4.07 OPAMBUILDTEST=1 \
      POST_INSTALL_HOOK="env TRAVIS=$TRAVIS TRAVIS_JOB_ID=$TRAVIS_JOB_ID bash -ex coverage.sh"
