build-and-test:
  image: ocaml/opam2:alpine-3.10-ocaml-4.08
  script:
    - opam pin --no-action ringo.dev .
    - opam install --deps-only ringo
    - opam pin --no-action ringo-lwt.dev .
    - opam depext ringo-lwt
    - opam install --deps-only ringo-lwt
    - dune build
    - dune runtest
    - opam install .
