language: c
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
env:
  global:
  - ALCOTEST_SHOW_ERRORS=1
  - PINS='repr.dev:. repr-bench.dev:. repr-fuzz.dev:. ppx_repr.dev:.'
  - DISTRO=debian-stable
  matrix:
  - OCAML_VERSION=4.08 PACKAGE="repr"
  - OCAML_VERSION=4.08 PACKAGE="repr-bench"
  - OCAML_VERSION=4.08 PACKAGE="repr-fuzz"
  - OCAML_VERSION=4.08 PACKAGE="ppx_repr"
