language: c
dist: xenial
sudo: false
addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - libssl-dev
before_install:
  - export OPAMYES=1
  - opam init
  - opam install -q -y dune
  - eval `opam config env`

script: dune build @default @runtest
