os: osx

language: generic

env:
  - SWITCH=4.10.0

before_script:
  - set -e
  - wget https://github.com/ocaml/opam/releases/download/2.0.6/opam-2.0.6-x86_64-macos
  - sudo mv opam-2.0.6-x86_64-macos /usr/local/bin/opam
  - sudo chmod a+x /usr/local/bin/opam
  - opam init -y --compiler $SWITCH --disable-sandboxing
  - eval `opam env`
  - ocaml -version
  - opam pin add -y git+https://github.com/lindig/lua-ml

script:
  - opam pin add -y --no-action soupault .
  - opam install -y --destdir . soupault

notifications:
  email:
    recipients:
      - daniil+soupault@baturin.org
    on_success: always
on_failure: always

addons:
  artifacts:
    working_dir: bin
