platform:
  - x86

environment:
  FORK_USER: ocaml
  FORK_BRANCH: master
  CYG_ROOT: C:\cygwin64
  PINS: gettext.0.4.0:. gettext-stub.0.4.0:. gettext-camomile.0.4.0:.
  OUNIT_CI: true
  matrix:
    - PACKAGE: gettext
    - PACKAGE: gettext-stub
    - PACKAGE: gettext-camomile

install:
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/$env:FORK_USER/ocaml-ci-scripts/$env:FORK_BRANCH/appveyor-install.ps1"))

build_script:
  - call %CYG_ROOT%\bin\bash.exe -l %APPVEYOR_BUILD_FOLDER%\appveyor-opam.sh
